### ISSUE TITLE
PS2 Model direct ltb to lta conversion - UnboundLocalError: local variable 'lod' referenced before assignment

### ISSUE THREAD

**Issue by StenApp** [Five-Damned-Dollarz/io_scene_lithtech#4]
> Python: Traceback (most recent call last):
  File "C:\Users\Sten\Downloads\blender-2.93.18-windows-x64\2.93\scripts\addons\Lithtech\converter.py", line 41, in execute
    model = PS2LTBModelReader().from_file(self.filepath)
  File "C:\Users\Sten\Downloads\blender-2.93.18-windows-x64\2.93\scripts\addons\Lithtech\reader_ltb_ps2.py", line 911, in from_file
    print("Final verticies ", len(lod.vertices))
UnboundLocalError: local variable 'lod' referenced before assignment

>location: <unknown location>:-1
[inthero_action.ltb.txt](https://github.com/Five-Damned-Dollarz/io_scene_lithtech/files/15300293/inthero_action.ltb.txt)

I like to convert the inthero.ltb model but get the above error.
What does the tool want?

**Comment by Five-Damned-Dollarz** [comment]
Incorrect scoping, should be fixed with the latest commit

**Comment by StenApp** [comment]
I updated the addonfiles in my Blender and tried, Modeledit shows no model.
Blender console shows this:

> -------------------------------
> LithTech LTB (PS2) Model Reader
> Loading ltb version 16
> ------------------------------------
> New Piece!
> HACK: Looking for Vector3 of 0.8f
> Could not find Vector3 of 0.8f, reached end of file.
> Processing Animation_0

![image](https://github.com/Five-Damned-Dollarz/io_scene_lithtech/assets/32524257/0bb39520-a997-48a1-a5be-220972cee4df)

Model hero_thief.ltb works, but has the distorted view when clicking on ConvertedfromPS2 animation
