### ISSUE TITLE
Neither pc_abc.bt nor pc_abc13.bt is working right for Nolf1 v12 models

### ISSUE THREAD

**Issue by StenApp** [Five-Damned-Dollarz/io_scene_lithtech#5]
Hi,

i'm trying to look at the files attached, especially deathbase.abc.
When i open it in the 010 Editor and apply the pc_abc or pc_abc13.bt files i get errors and data is misinterpreted.
Can you please have a look at it?
[hero_action.zip](https://github.com/Five-Damned-Dollarz/io_scene_lithtech/files/15396765/hero_action.zip)

**Comment by Five-Damned-Dollarz** [comment]
Uncomment LODWeight on line 112 in pc_abc.bt:
```c
struct Piece (uint32 LODCount) {
    uint16 MaterialIndex;
    float SpecularPower;
    float SpecularScale;
    //float LODWeight; <<- this
    uint16 Unknown;
    LTString Name;
    LOD LODs[LODCount] <optimize=false>;
};
```
